DEBUG 2024-12-03 22:07:39.814 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-03 22:07:39.815 UTC: 	 Running on: Linux lxplus982.cern.ch 5.14.0-503.14.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Nov 7 15:41:49 EST 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-03 22:07:39.815 UTC: 	 Using SINGULARITY image: el7:x86_64
DEBUG 2024-12-03 22:07:39.815 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-03 22:07:39.815 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-03 22:07:39.815 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/beozek/.crab3
INFO 2024-12-03 22:07:39.819 UTC: 	 Will use CRAB configuration file crab_config.py
DEBUG 2024-12-03 22:07:39.819 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-03 22:07:39.823 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-03 22:07:39.823 UTC: 	 Working area '/afs/cern.ch/user/b/beozek/private/CMSSW_10_6_28/src/MyAnalyzer/LHEMttbarAnalyzer/crab_projects/crab_LHEMttbarAnalyzer_RunIISummer20UL17' already exists 
Please change the requestName in the config file
ERROR 2024-12-03 22:07:39.823 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 330, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/b/beozek/private/CMSSW_10_6_28/src/MyAnalyzer/LHEMttbarAnalyzer/crab_projects/crab_LHEMttbarAnalyzer_RunIISummer20UL17' already exists 
Please change the requestName in the config file
INFO 2024-12-03 22:07:39.825 UTC: 	 Log file is /afs/cern.ch/user/b/beozek/private/CMSSW_10_6_28/src/MyAnalyzer/LHEMttbarAnalyzer/crab.log
DEBUG 2024-12-04 02:30:35.338 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-04 02:30:35.338 UTC: 	 Running on: Linux lxplus982.cern.ch 5.14.0-503.14.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Nov 7 15:41:49 EST 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-04 02:30:35.338 UTC: 	 Using SINGULARITY image: el7:x86_64
DEBUG 2024-12-04 02:30:35.338 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-04 02:30:35.338 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-04 02:30:35.339 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/beozek/.crab3
INFO 2024-12-04 02:30:35.339 UTC: 	 Will use CRAB configuration file crab_config_700_900.py
DEBUG 2024-12-04 02:30:35.339 UTC: 	 Loading CRAB configuration file.
DEBUG 2024-12-04 02:30:35.339 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2024-12-04 02:30:35.340 UTC: 	 Working area '/afs/cern.ch/user/b/beozek/private/CMSSW_10_6_28/src/MyAnalyzer/LHEMttbarAnalyzer/crab_projects/crab_LHEMttbarAnalyzer_MTT700to900_RunIISummer20UL17' already exists 
Please change the requestName in the config file
ERROR 2024-12-04 02:30:35.340 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 330, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/b/beozek/private/CMSSW_10_6_28/src/MyAnalyzer/LHEMttbarAnalyzer/crab_projects/crab_LHEMttbarAnalyzer_MTT700to900_RunIISummer20UL17' already exists 
Please change the requestName in the config file
INFO 2024-12-04 02:30:35.342 UTC: 	 Log file is /afs/cern.ch/user/b/beozek/private/CMSSW_10_6_28/src/MyAnalyzer/LHEMttbarAnalyzer/crab.log
DEBUG 2024-12-05 02:35:17.799 UTC: 	 CRAB Client version: v3.241125
DEBUG 2024-12-05 02:35:17.799 UTC: 	 Running on: Linux lxplus930.cern.ch 5.14.0-427.40.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Oct 4 15:22:45 EDT 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2024-12-05 02:35:17.799 UTC: 	 Using SINGULARITY image: el7:x86_64
DEBUG 2024-12-05 02:35:17.799 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2024-12-05 02:35:17.799 UTC: 	 Executing command: 'submit'
DEBUG 2024-12-05 02:35:17.799 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/beozek/.crab3
INFO 2024-12-05 02:35:17.817 UTC: 	 Will use CRAB configuration file cfg.py
DEBUG 2024-12-05 02:35:17.817 UTC: 	 Loading CRAB configuration file.
ERROR 2024-12-05 02:35:18.047 UTC: 	 Error while loading CRAB configuration:
Unable to find a Configuration object instance in file:
/afs/cern.ch/user/b/beozek/private/CMSSW_10_6_28/src/MyAnalyzer/LHEMttbarAnalyzer/cfg.py

Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
ERROR 2024-12-05 02:35:18.047 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 326, in __init__
    self.loadConfig(self.options.config, self.args)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 90, in loadConfig
    raise ConfigurationException(configmsg)
ConfigurationException: Error while loading CRAB configuration:
Unable to find a Configuration object instance in file:
/afs/cern.ch/user/b/beozek/private/CMSSW_10_6_28/src/MyAnalyzer/LHEMttbarAnalyzer/cfg.py

Please refer to https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ
See the ./crab.log file for more details.
The documentation about the CRAB configuration file can be found in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3ConfigurationFile
INFO 2024-12-05 02:35:18.063 UTC: 	 Log file is /afs/cern.ch/user/b/beozek/private/CMSSW_10_6_28/src/MyAnalyzer/LHEMttbarAnalyzer/crab.log
DEBUG 2025-02-05 05:02:40.815 UTC: 	 CRAB Client version: v3.241125
DEBUG 2025-02-05 05:02:40.815 UTC: 	 Running on: Linux lxplus973.cern.ch 5.14.0-503.15.1.el9_5.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Nov 14 15:45:31 EST 2024 x86_64 x86_64 x86_64 GNU/Linux
DEBUG 2025-02-05 05:02:40.815 UTC: 	 Using SINGULARITY image: el7:x86_64
DEBUG 2025-02-05 05:02:40.815 UTC: 	 Operating System: CentOS Linux 7 (Core)
DEBUG 2025-02-05 05:02:40.815 UTC: 	 Executing command: 'submit'
DEBUG 2025-02-05 05:02:40.815 UTC: 	 Found CRAB cache file /afs/cern.ch/user/b/beozek/.crab3
INFO 2025-02-05 05:02:40.816 UTC: 	 Will use CRAB configuration file crab_config.py
DEBUG 2025-02-05 05:02:40.816 UTC: 	 Loading CRAB configuration file.
DEBUG 2025-02-05 05:02:40.949 UTC: 	 Will use CRAB plugin ANALYSIS (i.e. will run an analysis job type).
ERROR 2025-02-05 05:02:40.949 UTC: 	 Working area '/afs/cern.ch/user/b/beozek/private/CMSSW_10_6_28/src/MyAnalyzer/LHEMttbarAnalyzer/crab_projects_SM_rwgth_test_3/crab_LHEMttbarAnalyzer_MTT0to700_RunIISummer20UL17_SM_rwgth_test_3' already exists 
Please change the requestName in the config file
ERROR 2025-02-05 05:02:40.949 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 157, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])  # the crab command to be executed
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/submit.py", line 37, in __init__
    SubCommand.__init__(self, logger, cmdargs, disable_interspersed_args=True)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/Commands/SubCommand.py", line 330, in __init__
    getattr(self.configuration.General, 'requestName', None))
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.241125.00/lib/CRABClient/ClientUtilities.py", line 392, in createWorkArea
    raise ConfigException("Working area '%s' already exists \nPlease change the requestName in the config file" % fullpath)
ConfigException: Working area '/afs/cern.ch/user/b/beozek/private/CMSSW_10_6_28/src/MyAnalyzer/LHEMttbarAnalyzer/crab_projects_SM_rwgth_test_3/crab_LHEMttbarAnalyzer_MTT0to700_RunIISummer20UL17_SM_rwgth_test_3' already exists 
Please change the requestName in the config file
INFO 2025-02-05 05:02:40.973 UTC: 	 Log file is /afs/cern.ch/user/b/beozek/private/CMSSW_10_6_28/src/MyAnalyzer/LHEMttbarAnalyzer/crab.log
